language: java
sudo: false

before_install:
  - git clone https://github.com/testmycode/tmc-langs.git
  - mvn clean install -U -Dmaven.test.skip=true -f tmc-langs/pom.xml
  - mvn install -Dmaven.test.skip=true

script:
  - mvn test
  - mvn checkstyle:check

after_success:
  - mvn clean cobertura:cobertura coveralls:report

jdk:
  - oraclejdk8
  - oraclejdk7

matrix:
  allow_failures:
    - os: osx

os:
  - linux
  # - osx

cache:
  directories:
    - "$HOME/.m2"

env:
  global:
  - secure: k2m3PY+eyz0uXHeJxScp2x/fPCrPDMPqyyTKe1BkWnx2j54Ci8o1unxwvAINwo4WJHBmGOxcfGGHBVMpZwmVHpneRI4U2XUWLk16X1Opm1a5BrslZpw63vx1G+RRZyG1q4hRyZYwHrcS8WIDSIJhzYlhDgSgykUPIwMHgO/M1JcaAhnR1X94NeVEsrgBDAaSbneEzeemO7pLU8dGa2YB+BoSs4nX85AiZUlMQyMRF+CPrgOaz0FewJXajwvok5Rp7cHG6s4nT79JV3cGg9Swf1TyE0gNChAuu7pMu6kGwvp0Kv1qD0DFnU1ZVdhd4QNlK8T7xXc7T9yTVDWOy3+J862tI6wpVxEr/oJS2KLfzJPQXBQMFYX1S6Znd939DNEQtb5eAyKKNz5ipMRzTqGEBZsXNlsgeTCN0BgVdmblJFDoa4o/wOoo2q1E7f99/q7xZ4tnvbTUDDdbOEByfdUkfUCxYKahH0bwR3CNYXIJRvC1Jl26P+sLF+pJUixc5wj1bSX54KQFulkYEYW/MrG2We0ICBLsJzpl9pRGnCFsdRITG3FSw6uvSEVHcDMrBsXszmSQ5Ms+LyeoLwHNueXI2fxvDaWDed7YBTdOIOvsBxpg0vCb1j7ZhyciOv4feHv2vGZSMfYvzFnO9nma8J0aJf0k8HguNnSBylNds1KXbb8=
  - secure: KmeJUko+QIWkZJCFQ+TpX704RO5YfN0/CYPOnFVysGIwfkQlJA9Nw4BxXNubbO53lBck3Cexbhgzj0B7kOPchKjbzycMLvUSXSGbh8Y9887rHliv/MSsQriJPGoQTIgqaF7I80Hl3UjWqvmavr8rljP/8u24jr3s7pj+Fhxw8mTJL4Zilg1/KqazfCf0s5CeLoTlR7EhSMjTgV+eBKG/cIpkbgxOshnd96J5PiHTumXFAYoJcGKfWvUjLNBMOai9zRbRtyGs++59Efc9G7mY8nPKG3oqPTePLLs/Yh0zjAG1+hjw+Ek8h6i/ytstQxaFM+ki6hT0W1QPd6u0EaeIM045SPofADr2DSMtcMnCwBuBxKEjdRmro3xC455Vi1zAWShUewaYq7oUvhji/73UA7h0XUSaYGg44jJGcgvNIq2QKdcE8Q+eB0/q+x7CbrvwuB1Z60ikmDjj1qsL54HeInhnyM0odzWcAYdNQdXTfOPOQJBw22nO/WmPJU6g9fJocyzCSE3sTShVm0cs4ewT7GQELYL9H5BSER3pWk4RUs6M1Y2IdGEC7xaZYQ8rBQ0Xv7O88FR6G2O65DgLve5/uW4zV55LBFE9S3WyJRNfnJp4TGRaZoMNfloMJzUYmBd04SH6RKVsP7s064W0/tpxHzbpA3ZVBdgExr2P2e+hcbc=
