language: java
sudo: false
before_install:
  - ./before_install.sh
after_success:
  - mvn clean cobertura:cobertura coveralls:report
matrix:
  allow_failures:
    - jdk: openjdk6
    - os: osx
os:
  - linux
  - osx

